version: '3'
services:
  backend:
    build: .
    volumes:
      - '.:/app'
    ports:
      - "5000:5000"
    env_file:
      - .env
    networks:
      - writeme-network
    depends_on:
      - redis_service
  redis_service:
    image: redis:alpine
    container_name: writeme-redis
    expose:
      - 6379
    networks:
      - writeme-network
networks:
    writeme-network:
        driver: bridge