GET http://localhost:5000/sections/css
Accept: application/json

###

GET http://localhost:5000/sections/level
Accept: application/json

###

GET http://localhost:5000/tree/css
Accept: application/json

###
# get language readmes

GET http://localhost:5000/repos/css
Accept: application/json

###

GET http://localhost:5000/load/css
Accept: application/json

###

GET http://localhost:5000/classify/css
Accept: application/json

###

GET http://localhost:5000/javascript
Accept: application/json

###

