GET http://localhost:5000/sections
Accept: application/json

###

GET http://localhost:5000/sections/level
Accept: application/json

###

GET http://localhost:5000/tree
Accept: application/json

###
# get language readmes

GET http://localhost:5000/c%23
Accept: application/json

###

GET http://localhost:5000/load/c%23
Accept: application/json

###

GET http://localhost:5000/classify/c%23
Accept: application/json

###

