import swiftSections from './languages/swift_sections';
import * as swiftReadmesTrees from './languages/readmes_trees.json';

import pythonSections from './languages/python_sections';
import * as pythonReadmesTrees from './languages/python_trees.json';

import csharpSections from './languages/csharp_sections';
import * as csharpReadmesTrees from './languages/csharp_trees.json';

import cppSections from './languages/cpp_sections';
import * as cppReadmesTrees from './languages/cpp_trees.json';

const supportedLanguages = {
  swift: {
    presentationName: 'Swift',
    sections: swiftSections,
    trees: swiftReadmesTrees,
  },
  python: {
    presentationName: 'Python',
    sections: pythonSections,
    trees: pythonReadmesTrees,
  },
  csharp: {
    presentationName: 'C#',
    sections: csharpSections,
    trees: csharpReadmesTrees,
  },
  cpp: {
    presentationName: 'C++',
    sections: cppSections,
    trees: cppReadmesTrees,
  },
};

export function getSections(language) {
  return [];
  return supportedLanguages[language].sections;
}

export function getTrees(language) {
  return {};
  return supportedLanguages[language].trees.default;
}

export function getLanguages() {
  return Object.keys(supportedLanguages).map(key => ({
    presentationName: supportedLanguages[key].presentationName,
    urlName: key,
  }));
}

export const githubLaguages = [
  'C',
  'C#',
  'C++',
  'CoffeeScript',
  'CSS',
  'Dart',
  'DM',
  'Elixir',
  'Go',
  'Groovy',
  'HTML',
  'Java',
  'JavaScript',
  'Kotlin',
  'Objective-C',
  'Perl',
  'PHP',
  'PowerShell',
  'Python',
  'Ruby',
  'Rust',
  'Scala',
  'Shell',
  'Swift',
  'TypeScript',
  '1C Enterprise',
  '4D',
  'ABAP',
  'ABAP CDS',
  'ABNF',
  'ActionScript',
  'Ada',
  'Adobe Font Metrics',
  'Agda',
  'AGS Script',
  'AIDL',
  'AL',
  'Alloy',
  'Alpine Abuild',
  'Altium Designer',
  'AMPL',
  'AngelScript',
  'Ant Build System',
  'ANTLR',
  'ApacheConf',
  'Apex',
  'API Blueprint',
  'APL',
  'Apollo Guidance Computer',
  'AppleScript',
  'Arc',
  'AsciiDoc',
  'ASL',
  'ASN.1',
  'ASP.NET',
  'AspectJ',
  'Assembly',
  'Asymptote',
  'ATS',
  'Augeas',
  'AutoHotkey',
  'AutoIt',
  'Avro IDL',
  'Awk',
  'Ballerina',
  'BASIC',
  'Batchfile',
  'Beef',
  'Befunge',
  'BibTeX',
  'Bicep',
  'Bison',
  'BitBake',
  'Blade',
  'BlitzBasic',
  'BlitzMax',
  'Bluespec',
  'Boo',
  'Boogie',
  'Brainfuck',
  'Brightscript',
  'Browserslist',
  'C-ObjDump',
  'C2hs Haskell',
  'Cabal Config',
  "Cap'n Proto",
  'CartoCSS',
  'Ceylon',
  'Chapel',
  'Charity',
  'ChucK',
  'CIL',
  'Cirru',
  'Clarion',
  'Classic ASP',
  'Clean',
  'Click',
  'CLIPS',
  'Clojure',
  'Closure Templates',
  'Cloud Firestore Security Rules',
  'CMake',
  'COBOL',
  'CODEOWNERS',
  'CodeQL',
  'ColdFusion',
  'ColdFusion CFC',
  'COLLADA',
  'Common Lisp',
  'Common Workflow Language',
  'Component Pascal',
  'CoNLL-U',
  'Cool',
  'Coq',
  'Cpp-ObjDump',
  'Creole',
  'Crystal',
  'CSON',
  'Csound',
  'Csound Document',
  'Csound Score',
  'CSV',
  'Cuda',
  'CUE',
  'Cue Sheet',
  'cURL Config',
  'CWeb',
  'Cycript',
  'Cython',
  'D',
  'D-ObjDump',
  'Dafny',
  'Darcs Patch',
  'DataWeave',
  'desktop',
  'Dhall',
  'Diff',
  'DIGITAL Command Language',
  'dircolors',
  'DirectX 3D File',
  'DNS Zone',
  'Dockerfile',
  'Dogescript',
  'DTrace',
  'Dylan',
  'E',
  'Eagle',
  'Easybuild',
  'EBNF',
  'eC',
  'Ecere Projects',
  'ECL',
  'ECLiPSe',
  'EditorConfig',
  'Edje Data Collection',
  'edn',
  'Eiffel',
  'EJS',
  'Elm',
  'Emacs Lisp',
  'EmberScript',
  'EML',
  'EQ',
  'Erlang',
  'F#',
  'F*',
  'Factor',
  'Fancy',
  'Fantom',
  'Faust',
  'FIGlet Font',
  'Filebench WML',
  'Filterscript',
  'fish',
  'Fluent',
  'FLUX',
  'Formatted',
  'Forth',
  'Fortran',
  'Fortran Free Form',
  'FreeBasic',
  'FreeMarker',
  'Frege',
  'Futhark',
  'G-code',
  'Game Maker Language',
  'GAML',
  'GAMS',
  'GAP',
  'GCC Machine Description',
  'GDB',
  'GDScript',
  'GEDCOM',
  'Gemfile.lock',
  'Genie',
  'Genshi',
  'Gentoo Ebuild',
  'Gentoo Eclass',
  'Gerber Image',
  'Gettext Catalog',
  'Gherkin',
  'Git Attributes',
  'Git Config',
  'GLSL',
  'Glyph',
  'Glyph Bitmap Distribution Format',
  'GN',
  'Gnuplot',
  'Golo',
  'Gosu',
  'Grace',
  'Gradle',
  'Grammatical Framework',
  'Graph Modeling Language',
  'GraphQL',
  'Graphviz (DOT)',
  'Groovy Server Pages',
  'Hack',
  'Haml',
  'Handlebars',
  'HAProxy',
  'Harbour',
  'Haskell',
  'Haxe',
  'HCL',
  'HiveQL',
  'HLSL',
  'HolyC',
  'HTML+ECR',
  'HTML+EEX',
  'HTML+ERB',
  'HTML+PHP',
  'HTML+Razor',
  'HTTP',
  'HXML',
  'Hy',
  'HyPhy',
  'IDL',
  'Idris',
  'Ignore List',
  'IGOR Pro',
  'ImageJ Macro',
  'Inform 7',
  'INI',
  'Inno Setup',
  'Io',
  'Ioke',
  'IRC log',
  'Isabelle',
  'Isabelle ROOT',
  'J',
  'Jasmin',
  'Java Properties',
  'Java Server Pages',
  'JavaScript+ERB',
  'JFlex',
  'Jinja',
  'Jison',
  'Jison Lex',
  'Jolie',
  'jq',
  'JSON',
  'JSON with Comments',
  'JSON5',
  'JSONiq',
  'JSONLD',
  'Jsonnet',
  'Julia',
  'Jupyter Notebook',
  'Kaitai Struct',
  'KiCad Layout',
  'KiCad Legacy Layout',
  'KiCad Schematic',
  'Kit',
  'KRL',
  'Kusto',
  'LabVIEW',
  'Lark',
  'Lasso',
  'Latte',
  'Lean',
  'Less',
  'Lex',
  'LFE',
  'LilyPond',
  'Limbo',
  'Linker Script',
  'Linux Kernel Module',
  'Liquid',
  'Literate Agda',
  'Literate CoffeeScript',
  'Literate Haskell',
  'LiveScript',
  'LLVM',
  'Logos',
  'Logtalk',
  'LOLCODE',
  'LookML',
  'LoomScript',
  'LSL',
  'LTspice Symbol',
  'Lua',
  'M',
  'M4',
  'M4Sugar',
  'Macaulay2',
  'Makefile',
  'Mako',
  'Markdown',
  'Marko',
  'Mask',
  'Mathematica',
  'MATLAB',
  'Maven POM',
  'Max',
  'MAXScript',
  'mcfunction',
  'Mercury',
  'Meson',
  'Metal',
  'Microsoft Developer Studio Project',
  'Microsoft Visual Studio Solution',
  'MiniD',
  'Mirah',
  'mIRC Script',
  'MLIR',
  'Modelica',
  'Modula-2',
  'Modula-3',
  'Module Management System',
  'Monkey',
  'Moocode',
  'MoonScript',
  'Motorola 68K Assembly',
  'MQL4',
  'MQL5',
  'MTML',
  'MUF',
  'mupad',
  'Muse',
  'Mustache',
  'Myghty',
  'nanorc',
  'NASL',
  'NCL',
  'Nearley',
  'Nemerle',
  'NEON',
  'nesC',
  'NetLinx',
  'NetLinx+ERB',
  'NetLogo',
  'NewLisp',
  'Nextflow',
  'Nginx',
  'Nim',
  'Ninja',
  'Nit',
  'Nix',
  'NL',
  'NPM Config',
  'NSIS',
  'Nu',
  'NumPy',
  'Nunjucks',
  'NWScript',
  'ObjDump',
  'Object Data Instance Notation',
  'Objective-C++',
  'Objective-J',
  'ObjectScript',
  'OCaml',
  'Odin',
  'Omgrofl',
  'ooc',
  'Opa',
  'Opal',
  'Open Policy Agent',
  'OpenCL',
  'OpenEdge ABL',
  'OpenQASM',
  'OpenRC runscript',
  'OpenSCAD',
  'OpenStep Property List',
  'OpenType Feature File',
  'Org',
  'Ox',
  'Oxygene',
  'Oz',
  'P4',
  'Pan',
  'Papyrus',
  'Parrot',
  'Parrot Assembly',
  'Parrot Internal Representation',
  'Pascal',
  'Pawn',
  'PEG.js',
  'Pep8',
  'Pic',
  'Pickle',
  'PicoLisp',
  'PigLatin',
  'Pike',
  'PlantUML',
  'PLpgSQL',
  'PLSQL',
  'Pod',
  'Pod 6',
  'PogoScript',
  'Pony',
  'PostCSS',
  'PostScript',
  'POV-Ray SDL',
  'PowerBuilder',
  'Prisma',
  'Processing',
  'Proguard',
  'Prolog',
  'Propeller Spin',
  'Protocol Buffer',
  'Public Key',
  'Pug',
  'Puppet',
  'Pure Data',
  'PureBasic',
  'PureScript',
  'Python console',
  'Python traceback',
  'q',
  'Q#',
  'QMake',
  'QML',
  'Qt Script',
  'Quake',
  'R',
  'Racket',
  'Ragel',
  'Raku',
  'RAML',
  'Rascal',
  'Raw token data',
  'RDoc',
  'Readline Config',
  'REALbasic',
  'Reason',
  'Rebol',
  'Record Jar',
  'Red',
  'Redcode',
  'Redirect Rules',
  'Regular Expression',
  "Ren'Py",
  'RenderScript',
  'ReScript',
  'reStructuredText',
  'REXX',
  'Rich Text Format',
  'Ring',
  'Riot',
  'RMarkdown',
  'RobotFramework',
  'robots.txt',
  'Roff',
  'Roff Manpage',
  'Rouge',
  'RPC',
  'RPM Spec',
  'RUNOFF',
  'Sage',
  'SaltStack',
  'SAS',
  'Sass',
  'Scaml',
  'Scheme',
  'Scilab',
  'SCSS',
  'sed',
  'Self',
  'SELinux Policy',
  'ShaderLab',
  'ShellSession',
  'Shen',
  'Sieve',
  'Singularity',
  'Slash',
  'Slice',
  'Slim',
  'Smali',
  'Smalltalk',
  'Smarty',
  'SmPL',
  'SMT',
  'Solidity',
  'Soong',
  'SourcePawn',
  'SPARQL',
  'Spline Font Database',
  'SQF',
  'SQL',
  'SQLPL',
  'Squirrel',
  'SRecode Template',
  'SSH Config',
  'Stan',
  'Standard ML',
  'Starlark',
  'Stata',
  'STON',
  'StringTemplate',
  'Stylus',
  'SubRip Text',
  'SugarSS',
  'SuperCollider',
  'Svelte',
  'SVG',
  'SWIG',
  'SystemVerilog',
  'Tcl',
  'Tcsh',
  'Tea',
  'Terra',
  'TeX',
  'Texinfo',
  'Text',
  'Textile',
  'TextMate Properties',
  'Thrift',
  'TI Program',
  'TLA',
  'TOML',
  'TSQL',
  'TSV',
  'TSX',
  'Turing',
  'Turtle',
  'Twig',
  'TXL',
  'Type Language',
  'Unified Parallel C',
  'Unity3D Asset',
  'Unix Assembly',
  'Uno',
  'UnrealScript',
  'UrWeb',
  'V',
  'Vala',
  'Valve Data Format',
  'VBA',
  'VBScript',
  'VCL',
  'Verilog',
  'VHDL',
  'Vim Help File',
  'Vim script',
  'Vim Snippet',
  'Visual Basic .NET',
  'Volt',
  'Vue',
  'Wavefront Material',
  'Wavefront Object',
  'wdl',
  'Web Ontology Language',
  'WebAssembly',
  'WebIDL',
  'WebVTT',
  'Wget Config',
  'Wikitext',
  'Windows Registry Entries',
  'wisp',
  'Wollok',
  'World of Warcraft Addon Data',
  'X BitMap',
  'X Font Directory Index',
  'X PixMap',
  'X10',
  'xBase',
  'XC',
  'XCompose',
  'XML',
  'XML Property List',
  'Xojo',
  'Xonsh',
  'XPages',
  'XProc',
  'XQuery',
  'XS',
  'XSLT',
  'Xtend',
  'Yacc',
  'YAML',
  'YANG',
  'YARA',
  'YASnippet',
  'ZAP',
  'Zeek',
  'ZenScript',
  'Zephir',
  'Zig',
  'ZIL',
  'Zimpl',
];

export default { supportedLanguages, getSections };
